version: '2'
services:
  packages:
   container_name: packages
   image: cnsoluciones/httpd:latest
   expose:
     - 80
   volumes:
     - ./user-data/html:/var/www/html
     - ./user-data/root/.gnupg:/root/.gnupg
     - /etc/localtime:/etc/localtime:ro
   environment:
     - "VIRTUAL_HOST=packages.cnsoluciones.com"
     - "VIRTUAL_PORT=80"
   restart: always
networks:
 default:
   external:
     name: nginx-net
